version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: demo_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fsrsDemo
    volumes:
      - demo_postgres_data:/var/lib/postgresql/data
    restart: always
  # https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.dev.yml
  next-app:
      container_name: ts-fsrs-demo
      build:
        context: .
        dockerfile: dev.Dockerfile
        network: host

      # Set environment variables directly in the docker-compose file
      environment:
        DATABASE_URL: ${DATABASE_URL}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

      # Set environment variables based on the .env file
      env_file:
        - .env
      volumes:
        - .:./app
      restart: always
      ports:
        - 3000:3000

volumes:
  demo_postgres_data:
